### ISSUE TITLE
@include "path/to/file.pml";

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/pml#1]
_@include_ inserts grammar definition from another file defined by the _path_:
```css
@include "path";
```

Includes can be recursive.

It's desired to track down the original PML file and the line number in the original PML file for each line in the resulting PML definition.

---

Examples:
```css
@include "a/b/c.pml";
@include "a.pml";
@include  "../../a/b/c.pml";
```

Below is the special case. The leading slash means lookup in the folder where the asset packages are stored:
```css
@include "/default/a/b/c.pml"
```

**Comment by polarkernel** [comment]
>  Includes can be recursive.

What do you mean by that? Normally, recursive includes are not allowed. For instance for a file A.pml
```
...
@inlcude "files/B.pml";
...
```

and a file B.pml
```
...
@inlcude "files/A.pml";
...
```
will start an infinite include loop. I will check for that and create an error message if found.

**Comment by polarkernel** [comment]
> ...  lookup in the folder where the asset packages are stored

Where will this location be defined?

**Comment by vvoovv** [comment]
> > Includes can be recursive.
> 
> What do you mean by that? Normally, recursive includes are not allowed. For instance for a file A.pml

I meant **hierarchical** rather than recursive. A can include B, B can include C, C can include D and so on

**Comment by vvoovv** [comment]
> > ...  lookup in the folder where the asset packages are stored
> 
> Where will this location be defined?

It should be an external parameter to the translator.

**Comment by polarkernel** [comment]
I have commited a first version of @include. The translator requires now an additional parameter:

``` 
python PML2PythonTranslator.py pmlstyle.pml pathToAssets
```

The path _pathToAssets_ must not have a slash at its end. The following features are included:

- Hierarchical inclusion to multiple levels is possible.
- Error messages include the file name and a local line number (track down).
- A leading slash in front of the file path leads to lookup in the assets folder.
- Recursive inlcusion is catched and produces an error message.
- A simple syntax check of the @include is implemented.

Let's see if this meets your requirements.

**Comment by vvoovv** [comment]
You are very fast!

Trying it out right now.

**Comment by vvoovv** [comment]
I've made a quick fix in the path:
https://github.com/prochitecture/pml/blob/master/PML_Preprocessor.py#L62

Otherwise it would not work if the path were in the absolute form.

**Comment by polarkernel** [comment]
Good to have an experienced programmer in the team!

**Comment by vvoovv** [comment]
I changed the regular expression in _PML_Preprocessor.py_ from
```python
        self.cmnt_patt = re.compile('//.*?\n')
```
to
```python
        self.cmnt_patt = re.compile('//.*\n?')
```

The previous regular expression couldn't detect a comment in the last line of a file without the next line symbol.
