### ISSUE TITLE
Error for a longer chain of attributes

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/pml#12]
This PML grammar works:

```css
facade(item.aaa.bbb) {

}
```

This PML produces an error:
```css
facade(item.aaa.bbb.ccc) {

}
```

The problem file is [attached](https://github.com/prochitecture/pml/files/9049238/pml_problem.txt).

**Comment by polarkernel** [comment]
> This PML produces an error:

Fixed and committed to master branch.

**Comment by vvoovv** [comment]
Thanks.

I added a test in _tests/test_condition.py_.
