### ISSUE TITLE
Bugs in first almost complete version

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/pml#4]
The first part is [here](https://github.com/vvoovv/pml/issues/8)

**Comment by vvoovv** [comment]
Scope modificator (_per_building(..)_, etc) can be applied to any part of the alternative expression or to the whole alternative expression.

See the attached PML file.

[scope.txt](https://github.com/prochitecture/pml/files/5068290/scope.txt)

**Comment by polarkernel** [comment]
> Scope modificator (per_building(..), etc) can be applied to any part of the alternative expression or to the whole alternative expression.

Should work now. per_building() was the only function that takes another function as argument within alternatives.

**Comment by vvoovv** [comment]
It outputs
```python
            claddingColor = Value(Alternatives(
                FromAttr("building:colour", FromAttr.Color)PerBuilding(,
                FromBldgAttr("building:colour", FromAttr.Color)),
                Conditional(
                    lambda item: item.getStyleBlockAttr("claddingMaterial") == "brick"PerBuilding(,
                    RandomWeighted( (((0.482, 0.259, 0.184, 1.0),1),((0.773, 0.463, 0.365, 1.0),1),((0.592, 0.424, 0.42, 1.0),1)) ))
                )PerBuilding(,
                RandomWeighted( (((0.482, 0.259, 0.184, 1.0),1),((0.773, 0.463, 0.365, 1.0),1),((0.592, 0.424, 0.42, 1.0),1)) ))
            ))
```

That raises a syntax error.

The output should be:
```python
            claddingColor = Value(Alternatives(
                PerBuilding(FromAttr("building:colour", FromAttr.Color)),
                FromBldgAttr("building:colour", FromAttr.Color)),
                Conditional(
                    lambda item: item.getStyleBlockAttr("claddingMaterial") == "brick",
                    PerBuilding(RandomWeighted( (((0.482, 0.259, 0.184, 1.0),1),((0.773, 0.463, 0.365, 1.0),1),((0.592, 0.424, 0.42, 1.0),1)) ))(
                ),
                PerBuilding(RandomWeighted( (((0.482, 0.259, 0.184, 1.0),1),((0.773, 0.463, 0.365, 1.0),1),((0.592, 0.424, 0.42, 1.0),1)) )))
            ))
```

**Comment by polarkernel** [comment]
That's weird? Using the code I commited yesterday, I get

```
            claddingColor = Value(Alternatives(
                FromAttr("building:colour", FromAttr.Color),
                PerBuilding(
                    FromBldgAttr("building:colour", FromAttr.Color)
                ),
                Conditional(
                    lambda item: item.getStyleBlockAttr("claddingMaterial") == "brick",
                    PerBuilding(
                        RandomWeighted( (((0.482, 0.259, 0.184, 1.0),1),((0.773, 0.463, 0.365, 1.0),1),((0.592, 0.424, 0.42, 1.0),1)) )
                    )
                ),
                PerBuilding(
                    RandomWeighted( (((0.482, 0.259, 0.184, 1.0),1),((0.773, 0.463, 0.365, 1.0),1),((0.592, 0.424, 0.42, 1.0),1)) )
                )
            ))
```

Did you get the changes of the two methods of PythonCoder.py starting [here](https://github.com/prochitecture/pml/blob/b385068b9aa691bec8af515e86841db50c2078f4/PythonCoder.py#L386)?

**Comment by vvoovv** [comment]
@polarkernel 
Sorry for the confusion. I used the old version of the _pml_ repo in the _blender-osm_ addon.
Yes, it works.

**Comment by vvoovv** [comment]
The following PML file gives a Python syntax error.

What is more important, the output is incorrect.

It should be
```
claddingColor = (1.0, 0.0, 0.0, 1.0)
```
intead of
```
claddingColor = Value(Constant((1.0, 0.0, 0.0, 1.0))
```

[main.txt](https://github.com/prochitecture/pml/files/5130634/main.txt)

**Comment by polarkernel** [comment]
> The following PML file gives a Python syntax error.

Fixed.

**Comment by vvoovv** [comment]
It works now. Thanks.

**Comment by vvoovv** [comment]
Parsing of empty markup fails (see the attached PML file):
```
item {
    markup: []
}
```
[empty_markup.txt](https://github.com/prochitecture/pml/files/5131490/empty_markup.txt)

**Comment by polarkernel** [comment]
> Parsing of empty markup fails

Fixed. 
What sense does that make? Couldn't the markup just get omitted?

**Comment by vvoovv** [comment]
I wanted to test something with and without markup and promptly switching between those two cases. That's how I encountered that bug.

**Comment by vvoovv** [comment]
It works now.
