### ISSUE TITLE
Level's indices

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/pml#9]
Currently the indices for a _Level_ style block are specified in its body:
```css
level {
    indices: [0,2];
}
```
or
```css
level {
    indices: [2,2];
}
```

However the level indices serve as a special condition rather than an attribute. A special syntax is required for them.

Below is the proposed syntax.

```css
level | 0:1 {
}
```

```css
level | 1: {
}
```

```css
level | :-2 {
}
```

For a single level index:

```css
level | 2 {
}
```

For a class definition:

```css
level@myclass | 0:1 {
}
```

For a condition:

```css
level@myclass | 0:1 [item.front] {
}
```

For roof levels only (the indices refer to the roof level indices):

```css
level | roof | 0:1 {
}
```

For all levels (the levels before the roof and the roof ones):

```css
level | all {
}
```

If the first index is given for the _all_ condition, it refers to the level index before the roof:

```css
level | all | 2: {
}
```

If the second index is given for the _all_ condition, it refers to the roof level index:

```css
level | all | :1 {
}
```

```css
level | all | 1:1 {
}
```

In the example above, the first index _1_ refers to the level index before the roof, while the second index refers to the roof level index.

**Comment by vvoovv** [comment]
Perhaps other separators can be used instead of the symbol _|_.

**Comment by polarkernel** [comment]
> However the level indices serve as a special condition rather than an attribute. A special syntax is required for them.

Could you please provide the translated Python results for this new syntax.

Am I right if I assume, that in the body between the curly brackets there can be attributes, similar to the other style elements?

**Comment by vvoovv** [comment]
> Am I right if I assume, that in the body between the curly brackets there can be attributes, similar to the other style elements?

Yes.

**Comment by vvoovv** [comment]
Indices is traslated to the _indices_ attribute.
_all_ is translated to the _allLevels_ attribute.
_roof_ is translated to the _roofLevels_ attribute.

For example,
```
level | 0:1 {
}
```
```python
Level(
  indices = (0,1),
  allLevels = False,
  roofLevels = False
)
```

Special cases:
* single index: `5` -> `indices = (5,5)`
* `:2` -> `indices = (0,2)`
* `2:` -> `indices = (2,-1)`

Perhaps the latter two cases `:2` and `2:` can be vorbidden for the simplicity.

**Comment by vvoovv** [comment]
An alternative syntax:

```
level@myclass[roof][0:1][item.front] {
}
```

I'd prefer it to the pipe separator _|_.

**Comment by vvoovv** [comment]
> Perhaps the latter two cases `:2` and `2:` can be vorbidden for the simplicity.

Yes, let's forget about that syntax. Only two explicit indices or a single index should be allowed.

**Comment by vvoovv** [comment]
I expect the syntax
```css
item[optional_special_condition_1]..[optional_special_condition_N][optional_real_conditon] {
}
```
can be used for other items (besides `level`) as well.

Examples of the special conditions for `level`: `[roof][0:3]`

**Comment by polarkernel** [comment]
> item[optional_special_condition_1]..[optional_special_condition_N][optional_real_conditon] {
}

Using square brackets, how can one distinguish between real and special conditions? We already used square brackets for (real) conditions:
```
@name "test";
	level@myclass [roof] {
	}
```
resulting in
```Python
styles = {
    "test" : [
        Level(
            defName = "myclass",
            condition = lambda item : roof
        )
    ]
}
```

**Comment by vvoovv** [comment]
> Using square brackets, how can one distinguish between real and special conditions? We already used square brackets for (real) conditions:

Check if the content in the square brackets for a _level_ is neither _roof_/_all_ nor _index1:index2_, then it's a real condition.

**Comment by vvoovv** [comment]
An alternative syntax:

```css
level@myclass[roof][0:1](item.front) {
}
```

I.e. the round brackets for a real condition.

**Comment by polarkernel** [comment]
> Check if the content in the square brackets for a level is neither roof/all nor index1:index2, then it's a real condition.

I don't like this solution, as it will lead to a complicated state machine in the Python coder.

> I.e. the round brackets for a real condition.

Much better. But why not the inverse, i.e. round brackets for special conditions? Then we would have upward compatibility to already existing styles.

>... can be used for other items (besides level) as well.

Should these other items be free or only specially defined ones? If they should be free, will their translations be equal (or similar) to the case of _level_?

**Comment by vvoovv** [comment]
> I don't like this solution, as it will lead to a complicated state machine in the Python coder.

Ok

> Much better. But why not the inverse, i.e. round brackets for special conditions? Then we would have upward compatibility to already existing styles.

Levels indices are a kind of slicing. It would be more natural to have the square brackets for slicing for those who know any popular programming language event a bit.

> Should these other items be free or only specially defined ones? If they should be free, will their translations be equal (or similar) to the case of _level_?

I can only tell that such items may appear in the future, e.g. for streets.

**Comment by polarkernel** [comment]
Just to confirm my understanding:

Am I right that only one or none of the conditions _roof_ and _all_ are allowed? If one of them is given, is its value translated to _True_, while the other is _False_? And when none are given, do both be _False_?

What about the indices, are they omitted in the translation, when they are not declared?

**Comment by vvoovv** [comment]
> Am I right that only one or none of the conditions _roof_ and _all_ are allowed? If one of them is given, is its value translated to _True_, while the other is _False_? And when none are given, do both be _False_?

Yes for all questions.

> What about the indices, are they omitted in the translation, when they are not declared?

Yes, they should be omitted in the translation.

**Comment by vvoovv** [comment]
I noticed the matrix
``` python
matrix = np.array(( segmentUnitVector, (segmentUnitVector[1], -segmentUnitVector[0]) ))
```
also flips the Y-axis.

I changed it to
```
matrix = np.array(( (segmentUnitVector[0], -segmentUnitVector[1]), (segmentUnitVector[1], segmentUnitVector[0]) ))
```

**Comment by vvoovv** [comment]
A strange result. Both the upper and the lower building edges are visible. The OSM file is [attached](https://github.com/prochitecture/pml/files/6204423/test_01.zip).

![image](https://user-images.githubusercontent.com/613295/112468772-bdcfbf00-8d79-11eb-9c48-97af74aa1181.png)

**Comment by polarkernel** [comment]
I committed a version with an implementation of this requirement. Please check if it does what you like to have.

**Comment by polarkernel** [comment]
I committed a version with an implementation of the special conditions for _Level_. Please check if it does what you like to have.

**Comment by vvoovv** [comment]
> Do the above two posts not belong to _blosm_ and not to _pml_?

Sorry, the above post belong to _blosm_. I'll copy them to _blosm_.

**Comment by vvoovv** [comment]
> Please check if it does what you like to have.

Yes, it does. Thank you so much!

I will create the automated tests to cover the majority of the possible combinations.

**Comment by vvoovv** [comment]
The only note. The following case doesn't make any sense (i.e. a single index with _all_):

```css
level[all][2]{
}
```

**Comment by polarkernel** [comment]
> The only note. The following case doesn't make any sense (i.e. a single index with all):

A grammar can't check such cases. It's like in Python, where you may write `arr[1][a][9]`, but before execution, the interprter can't check whether this makes sense or not. I implemented the desired syntax:
```
item[optional_special_condition_1]..[optional_special_condition_N](optional_real_conditon)
```
to be ready for future requests.

**Comment by vvoovv** [comment]
> I will create the automated tests to cover the majority of the possible combinations.

Added the automated tests:
[tests/test_level.py](https://github.com/prochitecture/pml/blob/master/tests/test_level.py)

**Comment by vvoovv** [comment]
I suggest using `@all` instead of `all` for consistency. For example:

```css
level[@all][0:1](item.front) {
    class: myclass;
}
```

**Comment by polarkernel** [comment]
> I suggest using @all instead of all for consistency.

Changed and committed. Accidently I wrote _@ALL_ in comment, but implemented it is _@all_. Couldn't change it in comment of commit.

**Comment by polarkernel** [comment]
Why does lower lettered _all_ get changed in _ALL_ when used with @?

**Comment by vvoovv** [comment]
> Why does lower lettered _all_ get changed in _ALL_ when used with @?

The character **@** is used to mark Github accounts. I guess the account https://github.com/all was created with the capital letters. Note that Github also inserted a link `@all` -> https://github.com/ALL
